### ISSUE TITLE
With the `Json` response, empty objects miss the first `{`

### ISSUE THREAD

**Issue by dzamlo** [sammhicks/picoserve#11]
With the following types:
```
#[derive(Serialize)]
struct EmptyResponse {}

#[derive(Serialize)]
struct SingleEmptyField {
    field: EmptyResponse,
}
```

If you try to return `Json(SingleEmptyField { field: EmptyResponse {}})`, you get `{"field":}}` as a response while the expected is `{"field":{}}`. If you try to return `Json(EmptyResponse {})` you get `}` instead of `{}`.

**Comment by sammhicks** [comment]
Good find, turns out my JSON serializer failed to correctly serialize any empty data structure!
