### ISSUE TITLE
Query parameters parsing is too strict

### ISSUE THREAD

**Issue by dzamlo** [sammhicks/picoserve#12]
For whatever reason, my client (a WASM app that use gloo-net to send the query) add an extra `&` at the end of the query.

The makes the parsing of query parameters fails with a `Bad Query` error.

The error originate at https://github.com/sammhicks/picoserve/blob/e5086aa61361e095aa9d3c5410d25be4c0faa4e8/src/url_encoded.rs#L473

I think we could be more forgiving and ignore empty URL segments at least at the end of the URL.

**Comment by sammhicks** [comment]
Sounds good, and thanks for the pull request :)
