### ISSUE TITLE
Borrow from request body in `FromRequest` impl

### ISSUE THREAD

**Issue by Ddystopia** [sammhicks/picoserve#19]
Hello, is there any way to express that I want to borrow from request body in `FromRequest` trait implementation? For example, getting `&str` instead of `heapless::String` in [example](https://github.com/sammhicks/picoserve/blob/5fb4315d5a93ac7dab808e1c28ad83cb2a40a05c/examples/form/src/main.rs#L8).

**Comment by sammhicks** [comment]
I unfortunately ran into lifetime problems when I tried to add support for FromRequest borrowing data from the HTTP request. It's on my desired feature list, but I'm not sure that it's feasible.

**Comment by sammhicks** [comment]
I might have a solution, currently in the development branch.
Although function handlers cannot borrow from requests, I've created helper macros to allow RequestHandlerService and PathRouterService to borrow from requests.
