### ISSUE TITLE
Error in `Content`

### ISSUE THREAD

**Issue by Ddystopia** [sammhicks/picoserve#28]
Hello, currently signature of `Content::write_content` suggests, that no other error could be return other than from writer, but I would like to return other errors. In my use case I'm reading from filesystem and it can give an error.

**Comment by sammhicks** [comment]
To further understand your requirements, where should this error be handled?

By the time that `Content::write_content` is called, the response header has already been sent, so then only option would be to cut the connection. If that's suitable, then I could have a simple "Abort" Error, which bubbles up until it is handled by `picoserve::serve` by disconnecting the socket.

Alternatively, the routing and handling code could be generic over an "AbortError" parameter which may be returned, and if returned by `Content::write_content`, the connection is aborted and the error is returned by `picoserve::serve`.

**Comment by sammhicks** [comment]
Closed due to lack of activity
