### ISSUE TITLE
Custom router to handle paths dynamically

### ISSUE THREAD

**Issue by scd31** [sammhicks/picoserve#34]
Hello,

I'd like to run a tile server on my esp32, serving tiles off of an SD card. This involves many thousands of files, and I cannot load all the file names into RAM. Instead, whenever I get a request, I'd like to check the SD card for the requested file and send it.

I believe this is doable using a custom type implementing `PathRouter`, and wrapping it in a `Router`. Unfortunately, I can't actually find a way to do this. It doesn't seem to be possible to instantiate a `Router<T>`, where `T` is my own type.

Anything I'm overlooking here? Otherwise I'd be happy to submit a PR to allow this.

Thanks!

**Comment by sammhicks** [comment]
The newly released [PathRouterService](https://docs.rs/picoserve/latest/picoserve/routing/trait.PathRouterService.html) and [Router::NestService](https://docs.rs/picoserve/latest/picoserve/routing/struct.Router.html#method.nest_service) should handle your use case.

Let me know how it goes! :)
