### ISSUE TITLE
Trying to create a "catch all" instance for 'Router'.

### ISSUE THREAD

**Issue by GustavToft** [sammhicks/picoserve#38]
Hello,

I'm currently developing a captive portal for a Pico W using `embassy`. It works when I hardcode responses for each device:

```rust
fn make_app() -> picoserve::Router<AppRouter> {
        picoserve::Router::new()
            .route(
                "/generate_204",
                get(|| picoserve::response::File::html(include_str!("connect.html"))),
            )
            .route(
                "/hotspot-detect.html",
                get(|| picoserve::response::File::html(include_str!("connect.html"))),
            )
            .route(
                "/connecttest.txt",
                get(|| picoserve::response::File::html(include_str!("connect.html"))),
            )
            .route(
                "/redirect",
                get(|| picoserve::response::File::html(include_str!("connect.html"))),
            )
    }
```

However, I can't figure out how to implement a catch-all route as to support any device.

Am I missing something, or is this just not yet implemented?

Thanks :)

**Comment by sammhicks** [comment]
It was not yet implemented, but is now!

Take a look at the newly created [`Router::from_service`](https://docs.rs/picoserve/latest/picoserve/routing/struct.Router.html#method.from_service).

**Comment by GustavToft** [comment]
Awesome! 

Thanks :)
