### ISSUE TITLE
How to parse a request body?

### ISSUE THREAD

**Issue by flyaruu** [sammhicks/picoserve#4]
I seem unable to parse a request body for a post.

I have created a type modeling my request, and created a custom FromRequest implementation, but can't figure out what kind of signature my handler function should have.

Can you perhaps add an example for this?

**Comment by sammhicks** [comment]
You should be able to use your custom type which implements FromRequest as a parameter to the handler function. I've now created an [example](https://github.com/sammhicks/picoserve/blob/main/examples/custom_extractor/src/main.rs) which should help.

To double check, a handler function:

- Must be async
- All its parameters must implement FromRequest
- Its return type must implement IntoResponse
