### ISSUE TITLE
Support multipart/x-mixed-replace responses 

### ISSUE THREAD

**Issue by Dominaezzz** [sammhicks/picoserve#43]
This is needed to implement an MJPEG stream. A typical multipart response looks something like this.

```
HTTP/1.1 200 OK
Content-Type: multipart/x-mixed-replace; boundary=myboundary

--myboundary
Content-Type: image/jpeg
Content-Length: 12345

[image 1 encoded jpeg data]


--myboundary
Content-Type: image/jpeg
Content-Length: 45678

[image 2 encoded jpeg data]
```

At the moment I can't implement this outside the library because the `Content` trait mandates that I provide a `content_length()` and I don't think there's any public way to create a (custom) `Response` without a `Content-Length` header.
So I guess this has to implemented inside the library similar to SSE and WebSockets?
I'm imagining something like the `EventStream` struct, A `MixedReplace` struct that takes two parameters, a boundary string and a `ContentSource` trait. The `ContentSource` trait just allows the user to write new `Content`s. (I'm not 100% sure if `Content` is the right trait for this, was just my first thought)

Side note: Firefox seems to not mind a `Content-Length` atm, so specifying a value like `1000000` allows me to workaround this issue while developing and I'm able to stream small JPEGs with this.

(This library is fantastic btw! Thanks for building it and sharing it!)

**Comment by sammhicks** [comment]
`multipart/x-mixed-replace` seems very different to regular HTTP requests and responses, even things like SSE and websockets, so I don't think that I want an implementation in picoserve itself.

Originally I decided to be relatively restrictive with what sorts of responses could be produced, hence Response having private fields, and Response::new requiring a body of `Content`, which requires a known length and MIME type, as opposed to the more general `Body`, with no such restrictions. This was both for developer ergonomics, in that it avoided footguns to do with forgetting to send the relevant headers, but also helped prevent me coding myself into a corner and having major breaking changes.

However, now that picoserve has been out for a while with a relatively stable structure, and that I've implemented support for automatically handing the "Connection" header and Keep-Alive, it seems a good time to provide functionality to create unusual responses that don't follow the standard pattern.

Thus, I introduce  the `CustomBody` trait and `CustomResponse` struct, similar to SSE, WebSockets, and Chunked Transfer Encoding. You should be able to implement `multipart/x-mixed-replace` on top of it.

It's currently in the `development` branch, let me know if it works for you!

**Comment by Dominaezzz** [comment]
Yes `CustomBody` and `CustomResponse` let me implement `multipart/x-mixed-replace`. I just tried it and it works like a charm.

Now that `Connection` is no longer a parameter of `write_content`, how can I tell when the connection is closed? I used to have some cleanup logic with `wait_for_disconnect`.

**Comment by Dominaezzz** [comment]
Ah sorry, I misrepresented my problem. 
My clean up logic is sync but even if I implement Drop, when I cancel the stream in the browser, the server hangs and hits a write timeout. During this hang time I can't handle more requests.

Ideally I'd like the write to be cancelled immediately, which I was previously doing myself by calling connection.wait_for_disconnect().

**Comment by sammhicks** [comment]
So, it seems that the cause of the delay (and then Write timeout) is due to the socket shutdown routine. The CustomBody is dropped as soon as the client disconnects, but then the write half of the socket is always flushed, which caused the delay and write timeout. The problem is that according to embassy net, you can't just close a socket, as the frame with the FIN flag set has not been sent, and they advise always flushing the write half.

I'm investigating possible alternative shutdown logic (and being generally a little confused at TCP :P ).

**Comment by sammhicks** [comment]
Well, that was an adventure!

While poking about, I found an error in the published version of `embassy_net` (it's fixed in `main`), and possibly another bug, though I'm not sure about the second.

I've a workaround, but can't publish it due to a git dependency, which crates.io disallows. Until the upstream bugfix is published, it'll have to remain in the newly created [`smart_shutdown`](https://github.com/sammhicks/picoserve/tree/smart_shutdown) branch.

Have a look, and hope it works for you!

**Comment by Dominaezzz** [comment]
Thanks for looking into it. I'll try and give it a whirl this weekend

**Comment by Dominaezzz** [comment]
Apologies for the late response but that commit does work for me, cancelling from the browser now immediately closes the connection on the server side. I can immediately handle other requests or restart the same request.
(I had to use the released/published versions of embassy)

Let me know once you've released it. This issue can be closed then.

**Comment by Dominaezzz** [comment]
Oh it's already released, I missed that. Thanks for the implementation! :heart:

**Comment by sammhicks** [comment]
@Dominaezzz I've removed the workaround as it's fixed upstream in `embassy-net`, are you OK to test the development branch (specifically e949baac424f0e32d65e58894c7ed9e31e4ec55b) to see if the connection is closed immediately?

My tests work, but it never hurts to have a second look...

**Comment by Dominaezzz** [comment]
ack, I'll give it a spin

**Comment by Dominaezzz** [comment]
Yup the connection is still closed immediately on the develop branch. Thanks!
