### ISSUE TITLE
Support chunked transfer encoding

### ISSUE THREAD

**Issue by Dominaezzz** [sammhicks/picoserve#44]
This allows either client or server send requests/responses without having to specify a `Content-Length` upfront.
This works by specifying a [Transfer-Encoding](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#transfer-encoding-response-header) of `chunked`, then the sender can send chunks of data and terminate the transfer by sending an empty chunk.
I'm particularly interested in chunked responses.

My specific use case for this is streaming JPEGs from an ESP32-S3.
When the ESP32-S3 is pulling JPEGs from a camera, it (usually) does not know the size of the image until the entire image is received into memory. Receiving the entire image into memory creates two problems; The first is latency, the image data should ideally be sent out ASAP after it's gotten from the camera. The second is image size, if the quality and width/height are large enough, the chip will be unable to fit the image in memory, which means it simply can't stream the image. Ideally the chip should be able to send out the image data ASAP to reduce the memory requirements.

I'm not sure what this should look like yet. Perhaps some kind of `ChunkWriter` I guess but I'm not sure how the terminating chunk should be handled yet.

(This library is fantastic btw! Thanks for building iand sharing it!)

**Comment by sammhicks** [comment]
I've written a draft implementation (see 8033a31), what do you think?

**Comment by Dominaezzz** [comment]
It looks great! It's more/less what I imagined. Thanks for throwing an implementation together so quickly.

My only comment is that it'd be convenient if the `ChunkWriter` itself also implemented the `Write` trait, and that way I could use the `write!` macro with it.

**Comment by sammhicks** [comment]
I've implemented `write_fmt` for `ChunkWriter`, which means that you'll be able to use the `write` macro, even though technically `ChunkWriter` doesn't implement `Write`. Does that meet your request?

https://github.com/sammhicks/picoserve/commit/f66c158b7a8b3fdb3f8b360e573d6074e9f782f2#diff-6186c6610b78b8b16d8526d10c5a2cfe8882b95b873e7a36a989de3e7b581599R34

**Comment by Dominaezzz** [comment]
Yes that's perfect thanks!

**Comment by Dominaezzz** [comment]
I've just used this in my application and it works like a charm. Last thing I'll ask for is a `flush()` method to ensure all previous chunks have been sent.

**Comment by sammhicks** [comment]
When you call `ChunkWriter::finalize`, the writer is flushed, other than that you shouldn't need to worry about flushing the buffers.
What scenario would you like to flush the buffers partway through writing a response?

**Comment by Dominaezzz** [comment]
In my case I'm doing both chunked encoding and mixed-replace. So I have an infinite chunked steam, and I want to flush after every replacement (a complete jpeg).

**Comment by Dominaezzz** [comment]
Ah, I just looked at the code and I see you've added an implicit flush after every chunk written. Would you mind if it were an explicit instead? My application doesn't need flush after each chunk, only after a couple dozen chunks.
Flushing after every chunk would reduce the throughput.

**Comment by sammhicks** [comment]
Resolved by b8622026a6c0d035c25c813741ed633565e26793, currently in the `development` branch, will be in the next release.

Writing chunks no longer adds an implicit flush, and there's a `flush` method on `ChunkWriter` which flushes the connection.

Please let me know if it works for you.

**Comment by Dominaezzz** [comment]
It's perfect, thanks!

**Comment by sammhicks** [comment]
picoserve v0.13.2 is released!
