### ISSUE TITLE
HTTPS suppot

### ISSUE THREAD

**Issue by reinismu** [sammhicks/picoserve#5]
Has anyone tried doing HTTPS?

**Comment by sammhicks** [comment]
It shouldn't be too much of a problem. picoserve is agnostic over the underlying protocol, so if you create structs that implement `embedded-io-async::Read` and `embedded-io-async::Write` that handles TLS, it should all just work.

But no, I've not tried HTTPS. In my case, I use nginx as a proxy, which also handles auth, and the connection between nginx and picoserve is unencrypted.
