### ISSUE TITLE
Can't run examples on Pi Pico

### ISSUE THREAD

**Issue by Levminer** [sammhicks/picoserve#50]
Hello!

I'm trying to run the examples on the Pi Pico W with a Raspberry debug probe.

I changed the runner to `runner = "probe-rs run --chip=RP2040"` configured `example_secrets.rs`

The code gets uploaded to the Pico correctly but I don't see any output and the Pico is not connected to wifi.

What am I missing?

**Comment by sammhicks** [comment]
The embassy examples host an Access Point, i.e. their own WiFi network, rather than connecting to an exist network.

**Comment by Levminer** [comment]
Thanks!
