### ISSUE TITLE
What's the best way to implement authentication?

### ISSUE THREAD

**Issue by tronje** [sammhicks/picoserve#61]
I want to add some very, very simple authentication, perhaps with a session token in a cookie, basically.

For that I guess I'd have the server respond with a `Set-Cookie` header to the correct login form request, and then I'd inspect the `Cookie` header for every subsequent request to see if the user is "logged in".

This should really be a very basic """security""" feature (note the many quotes), and doesn't need to protect anything critical.

How would I go about doing this? It looks to me like I may have to create custom request handlers that `impl RequestHandler` to get access to request headers. That's a lot more effort than just saying `get(some_function)` and `post(some_other_function)`... Thanks in advance :slightly_smiling_face:

**Comment by sammhicks** [comment]
Create a security token which implements `picoserve::extract::FromRequestParts`, and can verify the validity of the request and only return successfully if the request is authenticated correctly. `from_request_parts` has access to the State, so it can check against for example a list of currently logged in users, and the headers via `picoserve::request::RequestParts`.

For bonus security, have this token inside a module and have private internals, and have the only way to construct the token to be `FromRequestParts`, and have your authorized commands take in an instance on this security token as an argument. Thus you can use the type system to prove that authorized commands cannot be invoked from an unauthorized request.

**Comment by tronje** [comment]
Oh neat! Thanks a lot, that seems to be exactly what I need.

For anyone who finds this, here's a rough outline of the solution as code:

```rust
// the token to be extracted from the header, for my use case it's fine to be an empty struct
struct Token;

impl<'r, State> FromRequestParts<'r, State> for Token {
    type Rejection = Redirect;

    async fn from_request_parts(
        _state: &'r State,
        request_parts: &picoserve::request::RequestParts<'r>,
    ) -> Result<Self, Self::Rejection> {
        let cookie = request_parts
            .headers()
            .get("Cookie")
            .ok_or(Redirect::to("/login"))?;

        todo!("check that the cookie value is a valid session token")
    }
}

async fn root(_token: Token) -> impl IntoResponse {
    // if we get here, the user is logged in
    Response::ok(whatever)
}
```

And then what's neat is that you do not need to adapt your `Router` creation, even though the signature if a route handler changed from `async fn root()` to `async fn root(Token)`:

```rust
let router = Router::new().route("/", get(root));
```

Thanks again! I'll close this now.
