### ISSUE TITLE
Support Websocket Concurrency

### ISSUE THREAD

**Issue by Token-Thinker** [sammhicks/picoserve#8]
Hey,

Getting this weird error where I'm connecting to port 80 and have my routes setup for my app properly, but I can only access either the http or the websocket connection not both at the same time on the same port.

Thoughts?

Thanks

**Comment by Token-Thinker** [comment]
I manage to split the ports which got it working but since there isn't much support for client ids on the websocket side i thought to add multiple websocket servers however that didn't work either.

i can only spawn 1 http and 1 websocket is that correct?

**Comment by Token-Thinker** [comment]
also i'm not sure i can add the routes so that i can split the connection for the sockets.

for example below.

```rust
        let app = Router::new()
                .route(
                "/ws1",
                get(|upgrade: picoserve::response::ws::WebSocketUpgrade| {
                upgrade.on_upgrade(crate::network::websockets::WebsocketHandler {})
                }),
            )
            .route(
                "/ws2",
                get(|upgrade: picoserve::response::ws::WebSocketUpgrade| {
                upgrade.on_upgrade(crate::network::websockets::WebsocketHandler {})
                }),
            );
```

**Comment by Token-Thinker** [comment]
i agree with you, i'm using embassy to manage my tasks at the moment. 

i attempted to create new task for them to run concurrently however on ESP32 i can only run 1 http and 1 ws. when i attempt to run more than 1 it browns out. 

i'll attempt again as I 100% agree that is should work if i make multiple task that create different listening ports so that i can run various ws connections.

> Hi,
> 
> How are you managing tasks?
> 
> If you want to support multiple connections at the same time, so that for example you can have one or more websocket or SSE connection active while serving HTTP responses, you'll need multiple tasks running concurrently.
> 
> If there's an area of documentation that's unclear or needs further examples, please let me know and I can improve the documentation :)

**Comment by sammhicks** [comment]
From poking about the documentation, the panic with the message "adding a socket to a full SocketSet" originates from [smoltcp::iface::SocketSet::add](https://docs.rs/smoltcp/latest/src/smoltcp/iface/socket_set.rs.html#60-89). SocketSet is created from a slice of length `SOCK`, where `SOCK` is the generic constant of the created [embassy_net::StackResources](https://docs.embassy.dev/embassy-net/git/default/struct.StackResources.html).

Thus, the `SOCK` constant should have the same value as the number of embassy tasks which handle incoming connections.

Hope this helps :)

**Comment by Token-Thinker** [comment]
thanks, it is always the needle in the hay stack
